import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

class ApiService {
  Future<List<WeatherModel>> fetchData(String city) async {
    final response = await http.get(Uri.parse(
        'https://api.openweathermap.org/data/2.5/weather?q=' +
            city +
            '&appid=b2bcafb95a1516e9a4fc3d7b6314af23'));
    if (response.statusCode == 200) {
      return WeatherModel.fromJsonList([jsonDecode(response.body)]);
    } else {
      throw Exception('Failed to load Users');
    }
  }
}

class WeatherModel {
  late num id;
  late String name;
  late String main;
  late String icon;
  late num temp;
  late num humidity;
  late num speed;
  late num deg;

  WeatherModel({
    required this.id,
    required this.name,
    required this.main,
    required this.icon,
    required this.temp,
    required this.humidity,
    required this.speed,
    required this.deg,
  });

  WeatherModel.fromJson(Map map) {
    id = map['id'];
    name = map['name'];
    main = map['weather'][0]['main'];
    icon = map['weather'][0]['icon'];
    temp = map['main']['temp'];
    humidity = map['main']['humidity'];
    speed = map['wind']['speed'];
    deg = map['wind']['deg'];
  }

  static List<WeatherModel> fromJsonList(List<dynamic> jsonList) {
    List<WeatherModel> data = [];
    for (var element in jsonList) {
      data.add(WeatherModel.fromJson(element));
    }
    return data;
  }
}

//Middle East

List<String> citys = [
  "karachi",
  "Islamabad",
  "Balochistan",
  "Federally Administered Tribal Areas",
  "North-West Frontier Province",
  "Punjab",
  "Kabul",
  "Badakhshan",
  "Badghis",
  "Baghlan",
  "Balkh",
  "Bamian",
  "Farah",
  "Faryab",
  "Ghazni",
  "Ghowr",
  "Helmand",
  "Herat",
  "Jowzjan",
  "Kabol",
  "Kandahar",
  "Kapisa",
  "Khowst",
  "Konar",
  "Kondoz",
  "Laghman",
  "Lowgar",
  "Nangarhar",
  "Nimruz",
  "Nurestan",
  "Oruzgan",
  "Paktia",
  "Paktika",
  "Parvan",
  "Samangan",
  "Sar-e Pol",
  "Takhar",
  "Vardak",
  "Zabol",
  " Yerevan",
  "Aragatsotn",
  "Ararat",
  "Armavir",
  "Gegharkunik",
  "Kotayk",
  "Lorri",
  "Shirak",
  "Syunik",
  "Tavush",
  "Vayots Dzor",
  "Baku (Baki)",
  "Abseron",
  "Agcabadi",
  "Agdam",
  "Agdas",
  "Agstafa",
  "Agsu",
  "Ali Bayramli",
  "Astara",
  "Balakan",
  "Barda",
  "Beylaqan",
  "Bilasuvar",
  "Cabrayil",
  "Calilabad",
  "Daskasan",
  "Davaci",
  "Fuzuli",
  "Gadabay",
  "Ganca",
  "Goranboy",
  "Goycay",
  "Haciqabul",
  "Imisli",
  "Ismayilli",
  "Kalbacar",
  "Kurdamir",
  "Lacin",
  "Lankaran",
  "Lankaran",
  "Lerik",
  "Masalli",
  "Mingacevir",
  "Naftalan",
  "Naxcivan",
  "Neftcala",
  "Oguz",
  "Qabala",
  "Qax",
  "Qazax",
  "Qobustan",
  "Quba",
  "Qubadli",
  "Qusar",
  "Saatli",
  "Sabirabad",
  "Saki",
  "Saki",
  "Salyan",
  "Samaxi",
  "Samkir",
  "Samux",
  "Siyazan",
  "Sumqayit",
  "Susa",
  "Susa",
  "Tartar",
  "Tovuz",
  "Ucar",
  "Xacmaz",
  "Xankandi",
  "Xanlar",
  "Xizi",
  "Xocali",
  "Xocavand",
  "Yardimli",
  "Yevlax",
  "Yevlax",
  "Zangilan",
  "Zaqatala",
  "Zardab",
  "Manama",
  "Al Hadd",
  "Al Manamah",
  "Al Mintaqah al Gharbiyah",
  "Al Mintaqah al Wusta",
  "Al Mintaqah ash Shamaliyah",
  "Al Muharraq",
  "Ar Rifa wa al Mintaqah al Janubiyah",
  "Jidd Hafs",
  "Madinat Hamad",
  "Madinat Isa",
  "Juzur Hawar",
  "Sitrah",
  "Nicosia",
  "Famagusta",
  "Kyrenia",
  "Larnaca",
  "Limassol",
  "Paphos",
  "Tehran",
  "Ardabil",
  "Azarbayjan-e Gharbi",
  "Azarbayjan-e Sharqi",
  "Bushehr",
  "Chahar Mahall va Bakhtiari",
  "Esfahan",
  "Fars",
  "Gilan",
  "Golestan",
  "Hamadan",
  "Hormozgan",
  "Ilam",
  "Kerman",
  "Kermanshah",
  "Khorasan",
  "Khuzestan",
  "Kohkiluyeh va Buyer Ahmad",
  "Kordestan",
  "Lorestan",
  "Markazi",
  "Mazandaran",
  "Qazvin",
  "Qom",
  "Semnan",
  "Sistan va Baluchestan",
  "Yazd",
  "Zanjan",
  "Baghdad",
  "Al Anbar",
  "Al Basrah",
  "Al Muthanna",
  "Al Qadisiyah",
  "An Najaf",
  "Arbil",
  "As Sulaymaniyah",
  "At Tamim",
  "Babil",
  "Dahuk",
  "Dhi Qar",
  "Diyala",
  "Karbala",
  "Maysan",
  "Ninawa",
  "Salah ad Din",
  "Wasit",
  "Jerusalem",
  "Central",
  "Haifa",
  "Northern",
  "Southern",
  "Tel Aviv",
  "Amman",
  "Ajlun",
  "Al Aqabah",
  "Al Balqa",
  "Al Karak",
  "Al Mafraq",
  "At Tafilah",
  "Az Zarqa",
  "Irbid",
  "Jarash",
  "Maan",
  "Madaba",
  "Kuwait",
  "Al Ahmadi",
  "Al Farwaniyah",
  "Al Asimah",
  "Al Jahra",
  "Hawalli",
  "Bishkek Shaary",
  "Batken Oblasty",
  "Chuy Oblasty (Bishkek)",
  "Jalal-Abad Oblasty",
  "Naryn Oblasty",
  "Osh Oblasty",
  "Talas Oblasty",
  "Ysyk-Kol Oblasty (Karakol)",
  "Beirut",
  "Beyrouth",
  "Beqaa",
  "Liban-Nord",
  "Liban-Sud",
  "Mont-Liban",
  "Nabatiye",
  "Muscat",
  "Ad Dakhiliyah",
  "Al Batinah",
  "Al Wusta",
  "Ash Sharqiyah",
  "Az Zahirah",
  "Musandam",
  "Zufar",
  
  "Doha",
  "Ad Dawhah",
  "Al Ghuwayriyah",
  "Al Jumayliyah",
  "Al Khawr",
  "Al Wakrah",
  "Ar Rayyan",
  "Jarayan al Batinah",
  "Madinat ash Shamal",
  "Umm Salal",
  " '",
  "Riyadh",
  "Al Bahah",
  "Al Hudud ash Shamaliyah",
  "Al Jawf",
  "Al Madinah",
  "Al Qasim",
  "Ar Riyad",
  "Ash Sharqiyah (Eastern Province)",
  "Asir",
  "Hail",
  "Jizan",
  "Makkah",
  "Najran",
  "Tabuk",
  "Damascus",
  "Al Hasakah",
  "Al Ladhiqiyah",
  "Al Qunaytirah",
  "Ar Raqqah",
  "As Suwayda",
  "Dara",
  "Dayr az Zawr",
  "Dimashq",
  "Halab",
  "Hamah",
  "Hims",
  "Idlib",
  "Rif Dimashq",
  "Tartus",
  "Dushanbe",
  "Viloyati Mukhtori Kuhistoni Badakhshon",
  "Viloyati Khatlon",
  "Viloyati Sughd",
  "Ankara",
  "Adana",
  "Adiyaman",
  "Afyon",
  "Agri",
  "Aksaray",
  "Amasya",
  "Antalya",
  "Ardahan",
  "Artvin",
  "Aydin",
  "Balikesir",
  "Bartin",
  "Batman",
  "Bayburt",
  "Bilecik",
  "Bingol",
  "Bitlis",
  "Bolu",
  "Burdur",
  "Bursa",
  "Canakkale",
  "Cankiri",
  "Corum",
  "Denizli",
  "Diyarbakir",
  "Duzce",
  "Edirne",
  "Elazig",
  "Erzincan",
  "Erzurum",
  "Eskisehir",
  "Gaziantep",
  "Giresun",
  "Gumushane",
  "Hakkari",
  "Hatay",
  "Icel",
  "Igdir",
  "Isparta",
  "Istanbul",
  "Izmir",
  "Kahramanmaras",
  "Karabuk",
  "Karaman",
  "Kars",
  "Kastamonu",
  "Kayseri",
  "Kilis",
  "Kirikkale",
  "Kirklareli",
  "Kirsehir",
  "Kocaeli",
  "Konya",
  "Kutahya",
  "Malatya",
  "Manisa",
  "Mardin",
  "Mugla",
  "Mus",
  "Nevsehir",
  "Nigde",
  "Ordu",
  "Osmaniye",
  "Rize",
  "Sakarya",
  "Samsun",
  "Sanliurfa",
  "Siirt",
  "Sinop",
  "Sirnak",
  "Sivas",
  "Tekirdag",
  "Tokat",
  "Trabzon",
  "Tunceli",
  "Usak",
  "Van",
  "Yalova",
  "Yozgat",
  "Zonguldak  Buri",
  "Sisaket",
  "Songkhla",
  "Sukhothai",
  "Suphan Buri",
  "Surat Thani",
  "Surin",
  "Tak",
  "Trang",
  "Trat",
  "Ubon Ratchathani",
  "Udon Thani",
  "Uthai Thani",
  "Uttaradit",
  "Yala",
  "Yasothon",
  "Ashgabat",
  "Ahal Welayaty",
  "Balkan Welayaty",
  "Dasoguz Welayaty",
  "Labap Welayaty",
  "Mary Welayaty",
  " = '",
  "Abu Dhabi",
  "Abu Zaby (Abu Dhabi)",
  "Ajman",
  "Al Fujayrah",
  "Ash Shariqah (Sharjah)",
  "Dubayy (Dubai)",
  "Ras al Khaymah",
  "Umm al Qaywayn",
  "Tashkent (Toshkent)",
  "Andijon Viloyati",
  "Buxoro Viloyati",
  "Fargona Viloyati",
  "Jizzax Viloyati",
  "Namangan Viloyati",
  "Navoiy Viloyati",
  "Qashqadaryo Viloyati (Qarshi)",
  "Qaraqalpogiston Respublikasi",
  "Samarqand Viloyati",
  "Sirdaryo Viloyati (Guliston)",
  "Surxondaryo Viloyati (Termiz)",
  "Toshkent Shahri",
  "Toshkent Viloyati",
  "Xorazm Viloyati (Urganch)",
  "Sanaa",
  "Abyan",
  "Adan",
  "Al Bayda",
  "Al Hudaydah",
  "Al Jawf",
  "Al Mahrah",
  "Al Mahwit",
  "Dhamar",
  "Hadramawt",
  "Hajjah",
  "Ibb",
  "Lahij",
  "Marib",
  "Sadah",
  "Sana",
  "Shabwah",
  "Taizz"
];
